### ISSUE TITLE
マップ上のプラクティスとファイル名に差異あり？

### ISSUE THREAD

**Issue by WadaNoriaki** [kenjihiranabe/aaguide-jp#1]
Issue というものを使ってみたいので、一件登録します。

sashimi.txt という名前に興味があったので、開いてみたところ、1行目に「definition of done」と書いてありました。プラクティス名とファイル名が異なっているようです。

名前の違うものが他にもあるかもしれませんし、マップにないファイルもあるかもしれないですね。
（突き合わせをする気力が充実していないので、まずは気になることだけ、書いてみました）

**Comment by MakikoNakasato** [comment]
おっしゃる通りファイル名とプラクティス名の違うものがあります。Point
Estimationがnuts.txtだったり、マニアック(笑)な命名もありました。
ちなみに突き合わせはしてあって、現在のマップにないプラクティスのファイルには、その旨コメントを入れておきました。どなたかが気づかず翻訳してしまうともったいないなと思いましたので。
2015/10/14 22:35 "WadaNoriaki" notifications@github.com:

**Comment by WadaNoriaki** [comment]
突き合わせ情報、ありがとうございます。コメントを確認しました。Integration.txt などですね。
せっかくですので、nuts.txt のマニアックな由来を教えていただけるとうれしいで～す。

**Comment by MakikoNakasato** [comment]
nutsは灯台もと暗しですよ（笑）。
http://guide.agilealliance.org/guide/points-estimates-in.html
1ポイント＝1ナッツ（ピーナッツとかの）という意味合いもあったと思います。

sashimiについては、こっちのほうが分かりやすいかも。
http://agiletv.com/agile-glossary-s-z

**Comment by kenjihiranabe** [comment]
NUTS="Nebulous Units of Time" なんだー。初めて知った。Josh 命名かー。

**Comment by kenjihiranabe** [comment]
刺身は、ここでは、Vertical Slice （食べられる１つのスライス）なんだね。
- MVP(Minimum Viable Product)や、
- MMF(Minimum Marketable Feature)

ににてますね。ぼくの絵だとショートケーキだ。

**Comment by WadaNoriaki** [comment]
おお、ありがとうございます。ちなみにタブレットからもアクセスできました。
