### ISSUE TITLE
レビュー依頼：タイトル

### ISSUE THREAD

**Issue by MakikoNakasato** [kenjihiranabe/aaguide-jp#10]
@kenjihiranabe さん、[日本語タイトル](https://github.com/kenjihiranabe/aaguide-jp/blob/master/t/_list_JapaneseVer) のレビュー・修正をお願いします。

私が気になった点は、コメントを入れましたが、もちろんそれ以外も修正していただいて結構です。上のファイルを変更していただければ、そこからマップに反映しなおします。

**Comment by kenjihiranabe** [comment]
一回、レビュー入れました。不完全ですが、その場で気になったところの修正と、一行要約を全部にいれることを目指しました。
