### ISSUE TITLE
[volunteer.txt] that stands for the task in question. って、どう訳すんでしょう?

### ISSUE THREAD

**Issue by nobiinu-and** [kenjihiranabe/aaguide-jp#2]
全文は以下になります。

```
Signing up for a task is usually represented by an annotation 
on the [index card or sticky note](3C.html) that stands for the task in question.
```

**Comment by MakikoNakasato** [comment]
「対象のタスクを示す」とか、どうですか？

**Comment by WadaNoriaki** [comment]
in question = 議論中の
stand for = ～を意味する
という訳もあるようです。しかし、文の訳はあいかわらずわからないですが。。。（笑）

**Comment by nobiinu-and** [comment]
ありがとーございます。
「サインアップは、通常、インデックスカードや付箋紙に対象のタスクを示すメモ(多分名前のこと)を残す」 
意味は通りそう! もう少し頑張ってみます。

**Comment by nobiinu-and** [comment]
付箋紙にタスクの内容を書くのと、サインアップって、なんかちょっと違う気もするんだけど、ひとまず↑で行きます。
