### ISSUE TITLE
[simplicity.txt] タイトルの訳を追加してください

### ISSUE THREAD

**Issue by MakikoNakasato** [kenjihiranabe/aaguide-jp#8]
今村さん、simplicity.txtにタイトルの訳を追加してください。
（皆さんの訳してくださったタイトル部分を集めて、メトロマップに反映予定です）

**Comment by HiroakiImamura** [comment]
中佐藤さん
ご確認ありがとうございます。
Simplicity.txtの本文内に、タイトル「Rules of Simplicity」に対する訳を記入しました。

**Comment by MakikoNakasato** [comment]
ありがとうございます。確認しました。
